name: supabase_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.1
  supabase_flutter: ^1.10.25

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
