name: supabase_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.6
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.2
  go_router: ^14.2.1
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.1
  supabase_flutter: ^2.5.6

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.4

flutter:
  uses-material-design: true
